"""add invitations and contributor grants

Revision ID: 4ae73ed60970
Revises: 9f9514563882
Create Date: 2026-08-20 14:19:47.072272

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ae73ed60970'
down_revision: Union[str, Sequence[str], None] = '9f9514563882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('system_scope', sa.String(length=8), nullable=True),
    sa.Column(
        'subject_ids',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
        nullable=True,
    ),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_admin_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint(
        "system_scope IS NULL OR system_scope IN ('FR', 'EN', 'BOTH')",
        name='ck_admin_invitations_scope',
    ),
    sa.ForeignKeyConstraint(['invited_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_admin_invitations_email', 'admin_invitations', ['email'], unique=False)
    op.create_index(
        'ix_admin_invitations_token_hash', 'admin_invitations', ['token_hash'], unique=True
    )
    op.create_table('admin_subject_grants',
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('admin_id', 'subject_id')
    )
    op.create_index(
        'ix_admin_subject_grants_subject_id', 'admin_subject_grants', ['subject_id'], unique=False
    )
    op.alter_column('admin_roles', 'system_scope',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'BOTH'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_roles', 'system_scope',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'BOTH'::character varying"))
    op.drop_index('ix_admin_subject_grants_subject_id', table_name='admin_subject_grants')
    op.drop_table('admin_subject_grants')
    op.drop_index('ix_admin_invitations_token_hash', table_name='admin_invitations')
    op.drop_index('ix_admin_invitations_email', table_name='admin_invitations')
    op.drop_table('admin_invitations')
    # ### end Alembic commands ###
