"""create exam catalog models

Revision ID: 79756639559e
Revises: 
Create Date: 2026-08-19 04:19:39.820014

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '79756639559e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("system IN ('FR', 'EN')", name='ck_exams_system'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('parent_series_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('stream_group', sa.String(length=64), nullable=True),
    sa.Column('min_subjects', sa.Integer(), nullable=True),
    sa.Column('max_subjects', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['parent_series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_exam_id'), 'series', ['exam_id'], unique=False)
    op.create_index(
        op.f('ix_series_parent_series_id'), 'series', ['parent_series_id'], unique=False
    )
    op.create_table('subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_exam_id'), 'subjects', ['exam_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('parent_chapter_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('syllabus_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_chapters_parent_chapter_id'), 'chapters', ['parent_chapter_id'], unique=False
    )
    op.create_index(op.f('ix_chapters_subject_id'), 'chapters', ['subject_id'], unique=False)
    op.create_table('series_subjects',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_compulsory', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'subject_id')
    )
    op.create_index(
        'ix_series_subjects_subject_id', 'series_subjects', ['subject_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_series_subjects_subject_id', table_name='series_subjects')
    op.drop_table('series_subjects')
    op.drop_index(op.f('ix_chapters_subject_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_parent_chapter_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_subjects_exam_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_series_parent_series_id'), table_name='series')
    op.drop_index(op.f('ix_series_exam_id'), table_name='series')
    op.drop_table('series')
    op.drop_table('exams')
    # ### end Alembic commands ###
