"""add is_binding and subject_category

Revision ID: 9f9514563882
Revises: b78ba8e03e57
Create Date: 2026-08-19 05:46:15.897939

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f9514563882'
down_revision: Union[str, Sequence[str], None] = 'b78ba8e03e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'series',
        sa.Column('is_binding', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    )
    op.add_column(
        'series_subjects',
        sa.Column('subject_category', sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series_subjects', 'subject_category')
    op.drop_column('series', 'is_binding')
    # ### end Alembic commands ###
